DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS votelink;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS commentlink;
DROP TABLE IF EXISTS plan;
DROP TABLE IF EXISTS planlink;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS userlink;
TRUNCATE TABLE schema_migrations;